name: github_client
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化支持
  flutter_localizations:
    sdk: flutter
  # 持久化存储，iOS：NSUserdefault，Android：
  shared_preferences:
  # 网络请求
  dio:
  # 图片缓存
  cached_network_image:
  # 跨组件状态共享
#  provider:
  cupertino_icons: ^1.0.2
  provider:
  fluttertoast:
  flutter_screenutil:

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 生成json转model的类文件模板
  json_model: ^0.0.2
  # 提供了生成文件的通用命令
  build_runner: ^1.0.0
  # 为json_model生成的model类文件生成序列化模版 xxx.g.dart，里面定义了转model和json转换的方法
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/