# 应用包名称
name: first_flutter_app

# 描述
description: A new Flutter project.

# 版本号
version: 1.0.0+1

# sdk环境
environment:
  sdk: ">=2.1.0 <3.0.0"

# 依赖其他包或者插件
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # 添加新依赖，来自Pub仓库
  english_words: ^3.1.3

  # 添加本地依赖
  # package_test:
    # path: ../package_test/package_test.dart

# 开发环境依赖包或插件
dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter相关配置
flutter:
  uses-material-design: true
  assets:
    - imags/nodata.png


# dependencies的依赖包将作为App的源码的一部分参与编译，最终生成安装包
# dev_dependencies制作为开发阶段的工具包，提高开发，测试的效率，如自动化测试包